PRAGMA foreign_keys = ON;
INSERT INTO players (id, name, roles_json) VALUES
  ('adam-gilchrist', 'Adam Gilchrist', '["Wicketkeeper"]'),
  ('adam-lyth', 'Adam Lyth', '["Opener"]'),
  ('adil-rashid', 'Adil Rashid', '["Spinner"]'),
  ('alan-connolly', 'Alan Connolly', '["Fast Bowler"]'),
  ('alan-hurst', 'Alan Hurst', '["Fast Bowler"]'),
  ('alastair-cook', 'Alastair Cook', '["Opener"]'),
  ('alec-bedser', 'Alec Bedser', '["Fast Bowler"]'),
  ('alec-kennedy', 'Alec Kennedy', '["Fast Bowler"]'),
  ('alec-stewart', 'Alec Stewart', '["Wicketkeeper", "Opener"]'),
  ('alex-carey', 'Alex Carey', '["Wicketkeeper"]'),
  ('alfred-shaw', 'Alfred Shaw', '["Spinner"]'),
  ('allan-border', 'Allan Border', '["Top Order", "Middle Order", "Opener"]'),
  ('allan-lamb', 'Allan Lamb', '["Top Order", "Middle Order"]'),
  ('andrew-flintoff', 'Andrew Flintoff', '["All-rounder"]'),
  ('andrew-hilditch', 'Andrew Hilditch', '["Opener"]'),
  ('andrew-strauss', 'Andrew Strauss', '["Opener"]'),
  ('andrew-symonds', 'Andrew Symonds', '["All-rounder"]'),
  ('andy-caddick', 'Andy Caddick', '["Fast Bowler"]'),
  ('angus-fraser', 'Angus Fraser', '["Fast Bowler"]'),
  ('archie-maclaren', 'Archie MacLaren', '["Top Order"]'),
  ('arthur-carr', 'Arthur Carr', '["Middle Order"]'),
  ('arthur-gilligan', 'Arthur Gilligan', '["All-rounder"]'),
  ('arthur-mailey', 'Arthur Mailey', '["Spinner"]'),
  ('arthur-morris', 'Arthur Morris', '["Opener"]'),
  ('ashley-giles', 'Ashley Giles', '["Spinner"]'),
  ('ashley-mallett', 'Ashley Mallett', '["Spinner"]'),
  ('ashton-agar', 'Ashton Agar', '["Spinner"]'),
  ('ben-duckett', 'Ben Duckett', '["Opener"]'),
  ('ben-stokes', 'Ben Stokes', '["All-rounder"]'),
  ('bernard-bosanquet', 'Bernard Bosanquet', '["Spinner"]'),
  ('bert-oldfield', 'Bert Oldfield', '["Wicketkeeper"]'),
  ('bill-athey', 'Bill Athey', '["Opener", "Top Order"]'),
  ('bill-bowes', 'Bill Bowes', '["Fast Bowler"]'),
  ('bill-edrich', 'Bill Edrich', '["All-rounder"]'),
  ('bill-johnston', 'Bill Johnston', '["Fast Bowler"]'),
  ('bill-lawry', 'Bill Lawry', '["Opener"]'),
  ('bill-o-reilly', 'Bill O''Reilly', '["Spinner"]'),
  ('bill-ponsford', 'Bill Ponsford', '["Opener"]'),
  ('bill-voce', 'Bill Voce', '["Fast Bowler"]'),
  ('bill-whitty', 'Bill Whitty', '["Fast Bowler"]'),
  ('bill-woodfull', 'Bill Woodfull', '["Opener"]'),
  ('billy-murdoch', 'Billy Murdoch', '["Top Order", "Wicketkeeper"]'),
  ('bob-cowper', 'Bob Cowper', '["Top Order", "Middle Order"]'),
  ('bob-massie', 'Bob Massie', '["Fast Bowler"]'),
  ('bob-taylor', 'Bob Taylor', '["Wicketkeeper"]'),
  ('bob-willis', 'Bob Willis', '["Fast Bowler"]'),
  ('bob-wyatt', 'Bob Wyatt', '["Opener", "Top Order"]'),
  ('brad-haddin', 'Brad Haddin', '["Wicketkeeper"]'),
  ('brett-lee', 'Brett Lee', '["Fast Bowler"]'),
  ('brian-statham', 'Brian Statham', '["Fast Bowler"]'),
  ('brian-taber', 'Brian Taber', '["Wicketkeeper"]'),
  ('bruce-reid', 'Bruce Reid', '["Fast Bowler"]'),
  ('bruce-yardley', 'Bruce Yardley', '["All-rounder", "Spinner"]'),
  ('c-b-fry', 'C.B. Fry', '["Top Order"]'),
  ('cameron-bancroft', 'Cameron Bancroft', '["Opener"]'),
  ('cameron-green', 'Cameron Green', '["All-rounder"]'),
  ('charlie-macartney', 'Charlie Macartney', '["Middle Order", "All-rounder", "Top Order"]'),
  ('chris-broad', 'Chris Broad', '["Opener"]'),
  ('chris-lewis', 'Chris Lewis', '["All-rounder"]'),
  ('chris-old', 'Chris Old', '["Fast Bowler"]'),
  ('chris-rogers', 'Chris Rogers', '["Opener"]'),
  ('chris-woakes', 'Chris Woakes', '["Fast Bowler", "All-rounder"]'),
  ('chuck-fleetwood-smith', 'Chuck Fleetwood-Smith', '["Spinner"]'),
  ('clarence-everett', 'Clarence Everett', '["Fast Bowler"]'),
  ('clarrie-grimmett', 'Clarrie Grimmett', '["Spinner"]'),
  ('clem-hill', 'Clem Hill', '["Top Order"]'),
  ('colin-cowdrey', 'Colin Cowdrey', '["Middle Order"]'),
  ('colin-mcdonald', 'Colin McDonald', '["Opener"]'),
  ('craig-mcdermott', 'Craig McDermott', '["Fast Bowler"]'),
  ('cyril-washbrook', 'Cyril Washbrook', '["Opener"]'),
  ('damien-fleming', 'Damien Fleming', '["Fast Bowler"]'),
  ('damien-martyn', 'Damien Martyn', '["Middle Order"]'),
  ('darren-gough', 'Darren Gough', '["Fast Bowler"]'),
  ('david-allen', 'David Allen', '["Spinner"]'),
  ('david-boon', 'David Boon', '["Middle Order"]'),
  ('david-colley', 'David Colley', '["Fast Bowler"]'),
  ('david-gower', 'David Gower', '["Middle Order", "Top Order"]'),
  ('david-warner', 'David Warner', '["Opener"]'),
  ('denis-compton', 'Denis Compton', '["Top Order"]'),
  ('dennis-lillee', 'Dennis Lillee', '["Fast Bowler"]'),
  ('derek-pringle', 'Derek Pringle', '["Fast Bowler", "All-rounder"]'),
  ('derek-underwood', 'Derek Underwood', '["Spinner"]'),
  ('devon-malcolm', 'Devon Malcolm', '["Fast Bowler"]'),
  ('don-bradman', 'Don Bradman', '["Top Order"]'),
  ('doug-walters', 'Doug Walters', '["Middle Order", "All-rounder"]'),
  ('douglas-jardine', 'Douglas Jardine', '["Middle Order"]'),
  ('eoin-morgan', 'Eoin Morgan', '["Middle Order", "All-rounder"]'),
  ('ernie-mccormick', 'Ernie McCormick', '["Fast Bowler"]'),
  ('frank-laver', 'Frank Laver', '["All-rounder"]'),
  ('fred-leslie', 'Fred Leslie', '["Fast Bowler"]'),
  ('fred-spofforth', 'Fred Spofforth', '["Fast Bowler"]'),
  ('fred-trueman', 'Fred Trueman', '["Fast Bowler"]'),
  ('freddie-brown', 'Freddie Brown', '["Middle Order"]'),
  ('gary-cosier', 'Gary Cosier', '["Middle Order"]'),
  ('geoff-arnold', 'Geoff Arnold', '["Fast Bowler"]'),
  ('geoff-dymock', 'Geoff Dymock', '["Fast Bowler"]'),
  ('geoff-lawson', 'Geoff Lawson', '["Fast Bowler"]'),
  ('geoff-marsh', 'Geoff Marsh', '["Opener"]'),
  ('geoff-pullar', 'Geoff Pullar', '["Opener"]'),
  ('geoffrey-boycott', 'Geoffrey Boycott', '["Opener"]'),
  ('george-bonnor', 'George Bonnor', '["Opener"]'),
  ('george-geary', 'George Geary', '["Fast Bowler"]'),
  ('george-giffen', 'George Giffen', '["All-rounder"]'),
  ('george-hirst', 'George Hirst', '["All-rounder", "Fast Bowler"]'),
  ('george-mann', 'George Mann', '["Middle Order"]'),
  ('geraint-jones', 'Geraint Jones', '["Wicketkeeper"]'),
  ('gil-langley', 'Gil Langley', '["Wicketkeeper"]'),
  ('gladstone-small', 'Gladstone Small', '["Fast Bowler"]'),
  ('glenn-mcgrath', 'Glenn McGrath', '["Fast Bowler"]'),
  ('graeme-hick', 'Graeme Hick', '["Top Order"]'),
  ('graeme-swann', 'Graeme Swann', '["Spinner"]'),
  ('graeme-wood', 'Graeme Wood', '["Opener"]'),
  ('graham-dilley', 'Graham Dilley', '["Fast Bowler"]'),
  ('graham-gooch', 'Graham Gooch', '["Opener", "Middle Order"]'),
  ('graham-mckenzie', 'Graham McKenzie', '["Fast Bowler"]'),
  ('graham-thorpe', 'Graham Thorpe', '["Middle Order"]'),
  ('graham-yallop', 'Graham Yallop', '["Top Order", "Middle Order"]'),
  ('greg-blewett', 'Greg Blewett', '["Middle Order"]'),
  ('greg-chappell', 'Greg Chappell', '["Top Order"]'),
  ('gubby-allen', 'Gubby Allen', '["All-rounder"]'),
  ('harold-larwood', 'Harold Larwood', '["Fast Bowler"]'),
  ('harry-boyle', 'Harry Boyle', '["Fast Bowler"]'),
  ('harry-brook', 'Harry Brook', '["Middle Order"]'),
  ('hedley-verity', 'Hedley Verity', '["Spinner"]'),
  ('herbert-sutcliffe', 'Herbert Sutcliffe', '["Opener"]'),
  ('herbie-collins', 'Herbie Collins', '["Opener"]'),
  ('hugh-massie', 'Hugh Massie', '["Top Order"]'),
  ('ian-bell', 'Ian Bell', '["Middle Order"]'),
  ('ian-botham', 'Ian Botham', '["All-rounder"]'),
  ('ian-chappell', 'Ian Chappell', '["Top Order", "Middle Order"]'),
  ('ian-healy', 'Ian Healy', '["Wicketkeeper"]'),
  ('ian-johnson', 'Ian Johnson', '["Spinner"]'),
  ('ian-redpath', 'Ian Redpath', '["Opener", "Top Order"]'),
  ('ian-salisbury', 'Ian Salisbury', '["Spinner"]'),
  ('jack-blackham', 'Jack Blackham', '["Wicketkeeper"]'),
  ('jack-conway', 'Jack Conway', '["Middle Order"]'),
  ('jack-fingleton', 'Jack Fingleton', '["Top Order"]'),
  ('jack-gregory', 'Jack Gregory', '["Fast Bowler", "All-rounder"]'),
  ('jack-hobbs', 'Jack Hobbs', '["Opener"]'),
  ('jack-leach', 'Jack Leach', '["Spinner"]'),
  ('jack-newman', 'Jack Newman', '["Spinner"]'),
  ('jack-o-connor', 'Jack O''Connor', '["Spinner"]'),
  ('jack-richards', 'Jack Richards', '["Wicketkeeper"]'),
  ('jack-russell', 'Jack Russell', '["Wicketkeeper"]'),
  ('jack-ryder', 'Jack Ryder', '["Middle Order"]'),
  ('james-anderson', 'James Anderson', '["Fast Bowler"]'),
  ('james-ormond', 'James Ormond', '["Fast Bowler"]'),
  ('james-pattinson', 'James Pattinson', '["Fast Bowler"]'),
  ('jason-gillespie', 'Jason Gillespie', '["Fast Bowler"]'),
  ('jason-roy', 'Jason Roy', '["Opener"]'),
  ('jeff-hammond', 'Jeff Hammond', '["Fast Bowler"]'),
  ('jeff-thomson', 'Jeff Thomson', '["Fast Bowler"]'),
  ('jim-higgs', 'Jim Higgs', '["Wicketkeeper"]'),
  ('jim-laker', 'Jim Laker', '["Spinner"]'),
  ('joe-denly', 'Joe Denly', '["Middle Order"]'),
  ('joe-hardstaff', 'Joe Hardstaff', '["Middle Order"]'),
  ('joe-root', 'Joe Root', '["Top Order", "Middle Order"]'),
  ('jofra-archer', 'Jofra Archer', '["Fast Bowler"]'),
  ('john-emburey', 'John Emburey', '["Spinner"]'),
  ('john-gleeson', 'John Gleeson', '["Spinner"]'),
  ('john-inverarity', 'John Inverarity', '["All-rounder"]'),
  ('john-murray', 'John Murray', '["Wicketkeeper"]'),
  ('johnny-taylor', 'Johnny Taylor', '["Middle Order"]'),
  ('johnny-tyldesley', 'Johnny Tyldesley', '["Opener"]'),
  ('jonathan-trott', 'Jonathan Trott', '["Top Order"]'),
  ('jonny-bairstow', 'Jonny Bairstow', '["Wicketkeeper", "Middle Order"]'),
  ('jos-buttler', 'Jos Buttler', '["Wicketkeeper"]'),
  ('josh-hazlewood', 'Josh Hazlewood', '["Fast Bowler"]'),
  ('josh-tongue', 'Josh Tongue', '["Fast Bowler"]'),
  ('justin-langer', 'Justin Langer', '["Opener"]'),
  ('keith-miller', 'Keith Miller', '["All-rounder"]'),
  ('keith-stackpole', 'Keith Stackpole', '["Opener"]'),
  ('ken-barrington', 'Ken Barrington', '["Top Order"]'),
  ('ken-mackay', 'Ken Mackay', '["Middle Order", "All-rounder"]'),
  ('kevin-pietersen', 'Kevin Pietersen', '["Top Order", "Middle Order"]'),
  ('kim-hughes', 'Kim Hughes', '["Middle Order"]'),
  ('len-braund', 'Len Braund', '["All-rounder"]'),
  ('len-hutton', 'Len Hutton', '["Opener"]'),
  ('len-pascoe', 'Len Pascoe', '["Fast Bowler"]'),
  ('les-ames', 'Les Ames', '["Wicketkeeper"]'),
  ('leslie-ames', 'Leslie Ames', '["Wicketkeeper"]'),
  ('leslie-laws', 'Leslie Laws', '["Wicketkeeper"]'),
  ('lindsay-hassett', 'Lindsay Hassett', '["Middle Order"]'),
  ('marcus-trescothick', 'Marcus Trescothick', '["Opener"]'),
  ('mark-butcher', 'Mark Butcher', '["Top Order"]'),
  ('mark-taylor', 'Mark Taylor', '["Opener"]'),
  ('mark-wood', 'Mark Wood', '["Fast Bowler"]'),
  ('marnus-labuschagne', 'Marnus Labuschagne', '["Top Order"]'),
  ('martin-bicknell', 'Martin Bicknell', '["Fast Bowler"]'),
  ('matt-prior', 'Matt Prior', '["Wicketkeeper"]'),
  ('matthew-hayden', 'Matthew Hayden', '["Opener"]'),
  ('matthew-hoggard', 'Matthew Hoggard', '["Fast Bowler"]'),
  ('matthew-wade', 'Matthew Wade', '["Middle Order"]'),
  ('maurice-leyland', 'Maurice Leyland', '["Middle Order"]'),
  ('maurice-tate', 'Maurice Tate', '["All-rounder"]'),
  ('merv-hughes', 'Merv Hughes', '["Fast Bowler"]'),
  ('michael-atherton', 'Michael Atherton', '["Opener"]'),
  ('michael-clarke', 'Michael Clarke', '["Middle Order", "Top Order"]'),
  ('michael-hussey', 'Michael Hussey', '["Middle Order"]'),
  ('michael-kasprowicz', 'Michael Kasprowicz', '["Fast Bowler"]'),
  ('michael-vaughan', 'Michael Vaughan', '["Top Order"]'),
  ('mike-atherton', 'Mike Atherton', '["Opener"]'),
  ('mike-gatting', 'Mike Gatting', '["Top Order", "Middle Order"]'),
  ('mitchell-johnson', 'Mitchell Johnson', '["Fast Bowler"]'),
  ('mitchell-marsh', 'Mitchell Marsh', '["All-rounder"]'),
  ('mitchell-starc', 'Mitchell Starc', '["Fast Bowler"]'),
  ('moeen-ali', 'Moeen Ali', '["All-rounder", "Spinner"]'),
  ('monty-noble', 'Monty Noble', '["All-rounder"]'),
  ('nasser-hussain', 'Nasser Hussain', '["Middle Order"]'),
  ('nathan-lyon', 'Nathan Lyon', '["Spinner"]'),
  ('neil-foster', 'Neil Foster', '["Fast Bowler"]'),
  ('neil-harvey', 'Neil Harvey', '["Top Order"]'),
  ('neil-hawke', 'Neil Hawke', '["Fast Bowler"]'),
  ('norman-yardley', 'Norman Yardley', '["Middle Order"]'),
  ('ollie-pope', 'Ollie Pope', '["Top Order"]'),
  ('pat-cummins', 'Pat Cummins', '["Fast Bowler"]'),
  ('patsy-hendren', 'Patsy Hendren', '["Middle Order"]'),
  ('paul-collingwood', 'Paul Collingwood', '["Middle Order", "All-rounder"]'),
  ('paul-reiffel', 'Paul Reiffel', '["Fast Bowler"]'),
  ('paul-sheahan', 'Paul Sheahan', '["Middle Order"]'),
  ('percy-mcdonnell', 'Percy McDonnell', '["Middle Order"]'),
  ('percy-murphy', 'Percy Murphy', '["All-rounder"]'),
  ('peter-may', 'Peter May', '["Middle Order"]'),
  ('peter-siddle', 'Peter Siddle', '["Fast Bowler"]'),
  ('peter-toohey', 'Peter Toohey', '["Middle Order"]'),
  ('phil-defreitas', 'Phil DeFreitas', '["All-rounder", "Fast Bowler"]'),
  ('phil-edmonds', 'Phil Edmonds', '["Spinner"]'),
  ('phil-tufnell', 'Phil Tufnell', '["Spinner"]'),
  ('raman-subba-row', 'Raman Subba Row', '["Opener"]'),
  ('ranjitsinhji', 'Ranjitsinhji', '["Middle Order"]'),
  ('ray-bright', 'Ray Bright', '["Spinner"]'),
  ('ray-illingworth', 'Ray Illingworth', '["All-rounder"]'),
  ('ray-lindwall', 'Ray Lindwall', '["Fast Bowler"]'),
  ('rick-darling', 'Rick Darling', '["Top Order", "Middle Order"]'),
  ('ricky-ponting', 'Ricky Ponting', '["Top Order"]'),
  ('ritchie-benaud', 'Ritchie Benaud', '["All-rounder", "Spinner"]'),
  ('robin-smith', 'Robin Smith', '["Middle Order"]'),
  ('rod-marsh', 'Rod Marsh', '["Wicketkeeper"]'),
  ('rodney-hogg', 'Rodney Hogg', '["Fast Bowler"]'),
  ('ron-archer', 'Ron Archer', '["All-rounder", "Fast Bowler"]'),
  ('rory-burns', 'Rory Burns', '["Opener"]'),
  ('ross-edwards', 'Ross Edwards', '["Opener", "Middle Order"]'),
  ('roy-tattersall', 'Roy Tattersall', '["Spinner"]'),
  ('ryan-harris', 'Ryan Harris', '["Fast Bowler"]'),
  ('sammy-carter', 'Sammy Carter', '["Wicketkeeper"]'),
  ('scott-boland', 'Scott Boland', '["Fast Bowler"]'),
  ('shane-warne', 'Shane Warne', '["Spinner"]'),
  ('shane-watson', 'Shane Watson', '["All-rounder"]'),
  ('simon-jones', 'Simon Jones', '["Fast Bowler"]'),
  ('stan-mccabe', 'Stan McCabe', '["Middle Order"]'),
  ('stanley-jackson', 'Stanley Jackson', '["Middle Order"]'),
  ('steve-harmison', 'Steve Harmison', '["Fast Bowler"]'),
  ('steve-smith', 'Steve Smith', '["Middle Order"]'),
  ('steve-waugh', 'Steve Waugh', '["Middle Order", "All-rounder"]'),
  ('steven-finn', 'Steven Finn', '["Fast Bowler"]'),
  ('stuart-broad', 'Stuart Broad', '["Fast Bowler"]'),
  ('stuart-clark', 'Stuart Clark', '["Fast Bowler"]'),
  ('syd-gregory', 'Syd Gregory', '["Top Order"]'),
  ('sydney-barnes', 'Sydney Barnes', '["Fast Bowler"]'),
  ('ted-dexter', 'Ted Dexter', '["Top Order"]'),
  ('ted-mcdonald', 'Ted McDonald', '["Fast Bowler"]'),
  ('terry-alderman', 'Terry Alderman', '["Fast Bowler"]'),
  ('tibby-cotter', 'Tibby Cotter', '["Fast Bowler"]'),
  ('tim-robinson', 'Tim Robinson', '["Opener"]'),
  ('tim-wall', 'Tim Wall', '["Fast Bowler"]'),
  ('tom-graveney', 'Tom Graveney', '["Middle Order"]'),
  ('tom-moody', 'Tom Moody', '["All-rounder"]'),
  ('travis-head', 'Travis Head', '["Middle Order"]'),
  ('trevor-bailey', 'Trevor Bailey', '["All-rounder"]'),
  ('trevor-chappell', 'Trevor Chappell', '["All-rounder"]'),
  ('trevor-hohns', 'Trevor Hohns', '["Spinner"]'),
  ('usman-khawaja', 'Usman Khawaja', '["Opener"]'),
  ('vernon-royle', 'Vernon Royle', '["Opener"]'),
  ('vic-richardson', 'Vic Richardson', '["Middle Order"]'),
  ('victor-trumper', 'Victor Trumper', '["Opener"]'),
  ('wally-hammond', 'Wally Hammond', '["Top Order"]'),
  ('walter-robins', 'Walter Robins', '["All-rounder", "Spinner"]'),
  ('warren-bardsley', 'Warren Bardsley', '["Opener"]'),
  ('warwick-armstrong', 'Warwick Armstrong', '["All-rounder"]'),
  ('wilfred-rhodes', 'Wilfred Rhodes', '["All-rounder", "Spinner"]'),
  ('zak-crawley', 'Zak Crawley', '["Opener"]')
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  roles_json = excluded.roles_json;
