PRAGMA foreign_keys = ON;

ALTER TABLE teams ADD COLUMN competition TEXT NOT NULL DEFAULT 'ashes';

CREATE INDEX IF NOT EXISTS idx_teams_competition_mode_created_at
  ON teams(competition, mode, created_at);

INSERT OR IGNORE INTO players (id, name, roles_json) VALUES
  ('aamer-sohail', 'Aamer Sohail', '["Opener"]'),
  ('aaqib-javed', 'Aaqib Javed', '["Fast Bowler"]'),
  ('aaron-finch', 'Aaron Finch', '["Opener"]'),
  ('aasif-karim', 'Aasif Karim', '["Spinner"]'),
  ('adam-zampa', 'Adam Zampa', '["Spinner"]'),
  ('adeel-raja', 'Adeel Raja', '["Spinner"]'),
  ('aiden-markram', 'Aiden Markram', '["Middle Order"]'),
  ('alexei-kervezee', 'Alexei Kervezee', '["Opener"]'),
  ('ali-shah', 'Ali Shah', '["Opener"]'),
  ('alistair-campbell', 'Alistair Campbell', '["Top Order"]'),
  ('allan-donald', 'Allan Donald', '["Fast Bowler"]'),
  ('andy-flower', 'Andy Flower', '["Wicketkeeper"]'),
  ('andy-pycroft', 'Andy Pycroft', '["Middle Order"]'),
  ('andy-roberts', 'Andy Roberts', '["Fast Bowler"]'),
  ('aravinda-de-silva', 'Aravinda de Silva', '["Middle Order"]'),
  ('arjuna-ranatunga', 'Arjuna Ranatunga', '["Middle Order"]'),
  ('aryan-dutt', 'Aryan Dutt', '["Spinner"]'),
  ('asanka-gurusinha', 'Asanka Gurusinha', '["Top Order"]'),
  ('asghar-afghan', 'Asghar Afghan', '["Middle Order"]'),
  ('ashish-nehra', 'Ashish Nehra', '["Fast Bowler"]'),
  ('azmatullah-omarzai', 'Azmatullah Omarzai', '["All-rounder"]'),
  ('balwinder-sandhu', 'Balwinder Sandhu', '["Fast Bowler"]'),
  ('bas-de-leede', 'Bas de Leede', '["All-rounder"]'),
  ('bas-zuiderent', 'Bas Zuiderent', '["Middle Order"]'),
  ('bernard-loots', 'Bernard Loots', '["Fast Bowler"]'),
  ('boeta-dippenaar', 'Boeta Dippenaar', '["Middle Order"]'),
  ('brad-hogg', 'Brad Hogg', '["Spinner"]'),
  ('brijal-patel', 'Brijal Patel', '["Wicketkeeper"]'),
  ('chaminda-vaas', 'Chaminda Vaas', '["Fast Bowler"]'),
  ('clive-lloyd', 'Clive Lloyd', '["Middle Order"]'),
  ('colin-ackermann', 'Colin Ackermann', '["All-rounder"]'),
  ('colin-de-grandhomme', 'Colin de Grandhomme', '["All-rounder"]'),
  ('collins-obuya', 'Collins Obuya', '["Spinner"]'),
  ('craig-young', 'Craig Young', '["Fast Bowler"]'),
  ('daan-van-bunge', 'Daan van Bunge', '["Opener"]'),
  ('david-hemp', 'David Hemp', '["Middle Order"]'),
  ('david-houghton', 'David Houghton', '["Top Order"]'),
  ('david-miller', 'David Miller', '["Middle Order"]'),
  ('david-obuya', 'David Obuya', '["Middle Order", "Wicketkeeper"]'),
  ('dawid-malan', 'Dawid Malan', '["Opener"]'),
  ('dawlat-zadran', 'Dawlat Zadran', '["Fast Bowler"]'),
  ('dean-jones', 'Dean Jones', '["Top Order"]'),
  ('dean-minors', 'Dean Minors', '["Wicketkeeper"]'),
  ('delyone-borden', 'Delyone Borden', '["Middle Order"]'),
  ('desmond-haynes', 'Desmond Haynes', '["Opener"]'),
  ('dipak-chudasama', 'Dipak Chudasama', '["Opener"]'),
  ('dirk-nannes', 'Dirk Nannes', '["Fast Bowler"]'),
  ('dwayne-leverock', 'Dwayne Leverock', '["Spinner"]'),
  ('ed-joyce', 'Ed Joyce', '["Top Order"]'),
  ('eddo-brandes', 'Eddo Brandes', '["Fast Bowler"]'),
  ('edgar-schiferli', 'Edgar Schiferli', '["Fast Bowler"]'),
  ('eric-szwarczynski', 'Eric Szwarczynski', '["Opener"]'),
  ('fazalhaq-farooqi', 'Fazalhaq Farooqi', '["Fast Bowler"]'),
  ('feiko-kloppenburg', 'Feiko Kloppenburg', '["All-rounder"]'),
  ('gary-crocker', 'Gary Crocker', '["Fast Bowler"]'),
  ('gary-kirsten', 'Gary Kirsten', '["Top Order"]'),
  ('gary-wilson', 'Gary Wilson', '["Middle Order"]'),
  ('gautam-gambhir', 'Gautam Gambhir', '["Top Order"]'),
  ('george-dockrell', 'George Dockrell', '["Spinner"]'),
  ('gerald-coetzee', 'Gerald Coetzee', '["Fast Bowler"]'),
  ('glenn-maxwell', 'Glenn Maxwell', '["All-rounder"]'),
  ('gordon-greenidge', 'Gordon Greenidge', '["Opener"]'),
  ('graeme-smith', 'Graeme Smith', '["Opener"]'),
  ('grant-flower', 'Grant Flower', '["Opener"]'),
  ('grant-paterson', 'Grant Paterson', '["Wicketkeeper"]'),
  ('greg-dyer', 'Greg Dyer', '["Wicketkeeper"]'),
  ('guy-whittall', 'Guy Whittall', '["All-rounder"]'),
  ('hamid-hassan', 'Hamid Hassan', '["Fast Bowler"]'),
  ('harbhajan-singh', 'Harbhajan Singh', '["Spinner"]'),
  ('hardik-pandya', 'Hardik Pandya', '["All-rounder"]'),
  ('hashan-tillakaratne', 'Hashan Tillakaratne', '["Middle Order"]'),
  ('hashmatullah-shahidi', 'Hashmatullah Shahidi', '["Middle Order"]'),
  ('hazratullah-zazai', 'Hazratullah Zazai', '["Opener"]'),
  ('heath-streak', 'Heath Streak', '["All-rounder"]'),
  ('heinrich-klaasen', 'Heinrich Klaasen', '["Middle Order"]'),
  ('henry-nicholls', 'Henry Nicholls', '["Opener"]'),
  ('henry-olonga', 'Henry Olonga', '["Fast Bowler"]'),
  ('herschelle-gibbs', 'Herschelle Gibbs', '["Opener"]'),
  ('hitesh-modi', 'Hitesh Modi', '["Middle Order"]'),
  ('iain-butchart', 'Iain Butchart', '["All-rounder"]'),
  ('ibrahim-zadran', 'Ibrahim Zadran', '["Opener"]'),
  ('imran-khan', 'Imran Khan', '["All-rounder"]'),
  ('inzamam-ul-haq', 'Inzamam-ul-Haq', '["Middle Order"]'),
  ('irving-romaine', 'Irving Romaine', '["Top Order"]'),
  ('jacques-kallis', 'Jacques Kallis', '["All-rounder"]'),
  ('james-neesham', 'James Neesham', '["All-rounder"]'),
  ('jasprit-bumrah', 'Jasprit Bumrah', '["Fast Bowler"]'),
  ('javed-miandad', 'Javed Miandad', '["Top Order"]'),
  ('jeff-dujon', 'Jeff Dujon', '["Wicketkeeper"]'),
  ('jeroen-smits', 'Jeroen Smits', '["Middle Order"]'),
  ('joel-garner', 'Joel Garner', '["Fast Bowler"]'),
  ('john-mooney', 'John Mooney', '["All-rounder"]'),
  ('john-traicos', 'John Traicos', '["Spinner"]'),
  ('josh-inglis', 'Josh Inglis', '["Wicketkeeper"]'),
  ('kagiso-rabada', 'Kagiso Rabada', '["Fast Bowler"]'),
  ('kane-williamson', 'Kane Williamson', '["Top Order"]'),
  ('kapil-dev', 'Kapil Dev', '["All-rounder"]'),
  ('kennedy-otieno', 'Kennedy Otieno', '["Opener"]'),
  ('keshav-maharaj', 'Keshav Maharaj', '["Spinner"]'),
  ('kevin-curran', 'Kevin Curran', '["All-rounder"]'),
  ('kevin-hurdle', 'Kevin Hurdle', '["Fast Bowler"]'),
  ('kevin-o-brien', 'Kevin O''Brien', '["All-rounder"]'),
  ('kirti-azad', 'Kirti Azad', '["All-rounder"]'),
  ('kl-rahul', 'KL Rahul', '["Middle Order", "Wicketkeeper"]'),
  ('krishnamachari-srikkanth', 'Krishnamachari Srikkanth', '["Opener"]'),
  ('kuldeep-yadav', 'Kuldeep Yadav', '["Spinner"]'),
  ('kumar-dharmasena', 'Kumar Dharmasena', '["All-rounder"]'),
  ('lance-klusener', 'Lance Klusener', '["All-rounder"]'),
  ('larry-gomes', 'Larry Gomes', '["Middle Order"]'),
  ('liam-plunkett', 'Liam Plunkett', '["Fast Bowler"]'),
  ('lionel-cann', 'Lionel Cann', '["All-rounder"]'),
  ('lockie-ferguson', 'Lockie Ferguson', '["Fast Bowler"]'),
  ('lungi-ngidi', 'Lungi Ngidi', '["Fast Bowler"]'),
  ('luuk-van-troost', 'Luuk van Troost', '["Wicketkeeper"]'),
  ('madan-lal', 'Madan Lal', '["Fast Bowler"]'),
  ('mahmudullah', 'Mahmudullah', '["All-rounder"]'),
  ('makhaya-ntini', 'Makhaya Ntini', '["Fast Bowler"]'),
  ('malachi-jones', 'Malachi Jones', '["Fast Bowler"]'),
  ('malcolm-marshall', 'Malcolm Marshall', '["Fast Bowler"]'),
  ('marco-jansen', 'Marco Jansen', '["All-rounder"]'),
  ('marcus-stoinis', 'Marcus Stoinis', '["All-rounder"]'),
  ('mark-boucher', 'Mark Boucher', '["Wicketkeeper"]'),
  ('martin-guptill', 'Martin Guptill', '["Opener"]'),
  ('martin-suji', 'Martin Suji', '["Fast Bowler"]'),
  ('mashrafe-mortaza', 'Mashrafe Mortaza', '["Fast Bowler"]'),
  ('matt-henry', 'Matt Henry', '["Fast Bowler"]'),
  ('maurice-odumbe', 'Maurice Odumbe', '["All-rounder"]'),
  ('max-o-dowd', 'Max O''Dowd', '["Opener"]'),
  ('max-sorensen', 'Max Sorensen', '["Fast Bowler"]'),
  ('mehidy-hasan', 'Mehidy Hasan', '["Spinner"]'),
  ('michael-holding', 'Michael Holding', '["Fast Bowler"]'),
  ('mitchell-santner', 'Mitchell Santner', '["Spinner"]'),
  ('mohammad-nabi', 'Mohammad Nabi', '["All-rounder"]'),
  ('mohammed-shami', 'Mohammed Shami', '["Fast Bowler"]'),
  ('mohammed-siraj', 'Mohammed Siraj', '["Fast Bowler"]'),
  ('mohinder-amarnath', 'Mohinder Amarnath', '["All-rounder"]'),
  ('moin-khan', 'Moin Khan', '["Wicketkeeper"]'),
  ('mosaddek-hossain', 'Mosaddek Hossain', '["Middle Order"]'),
  ('mpumelelo-mbangwa', 'Mpumelelo Mbangwa', '["Fast Bowler"]'),
  ('ms-dhoni', 'MS Dhoni', '["Wicketkeeper"]'),
  ('mudassar-bukhari', 'Mudassar Bukhari', '["All-rounder"]'),
  ('mujeeb-ur-rahman', 'Mujeeb Ur Rahman', '["Spinner"]'),
  ('munaf-patel', 'Munaf Patel', '["Fast Bowler"]'),
  ('mushfiqur-rahim', 'Mushfiqur Rahim', '["Wicketkeeper"]'),
  ('mushtaq-ahmed', 'Mushtaq Ahmed', '["Spinner"]'),
  ('mustafizur-rahman', 'Mustafizur Rahman', '["Fast Bowler"]'),
  ('muttiah-muralitharan', 'Muttiah Muralitharan', '["Spinner"]'),
  ('najibullah-zadran', 'Najibullah Zadran', '["Middle Order"]'),
  ('nathan-bracken', 'Nathan Bracken', '["Fast Bowler"]'),
  ('naveen-ul-haq', 'Naveen-ul-Haq', '["Fast Bowler"]'),
  ('neil-johnson', 'Neil Johnson', '["All-rounder"]'),
  ('niall-o-brien', 'Niall O''Brien', '["Wicketkeeper"]'),
  ('noor-ahmad', 'Noor Ahmad', '["Spinner"]'),
  ('noor-ali-zadran', 'Noor Ali Zadran', '["Opener"]'),
  ('oliver-pitcher', 'Oliver Pitcher', '["Opener"]'),
  ('patrick-shah', 'Patrick Shah', '["Middle Order"]'),
  ('paul-stirling', 'Paul Stirling', '["Opener"]'),
  ('paul-strang', 'Paul Strang', '["Spinner"]'),
  ('paul-van-meekeren', 'Paul van Meekeren', '["Fast Bowler"]'),
  ('peter-borren', 'Peter Borren', '["All-rounder"]'),
  ('peter-ongondo', 'Peter Ongondo', '["Fast Bowler"]'),
  ('phil-carlson', 'Phil Carlson', '["Fast Bowler"]'),
  ('pieter-seelaar', 'Pieter Seelaar', '["Spinner"]'),
  ('pommie-mbangwa', 'Pommie Mbangwa', '["Fast Bowler"]'),
  ('pramodya-wickramasinghe', 'Pramodya Wickramasinghe', '["Fast Bowler"]'),
  ('quinton-de-kock', 'Quinton de Kock', '["Opener", "Wicketkeeper"]'),
  ('rahmanullah-gurbaz', 'Rahmanullah Gurbaz', '["Opener", "Wicketkeeper"]'),
  ('rahmat-shah', 'Rahmat Shah', '["Top Order"]'),
  ('rajab-ali', 'Rajab Ali', '["Spinner"]'),
  ('rameez-raja', 'Rameez Raja', '["Opener"]'),
  ('rashid-khan', 'Rashid Khan', '["Spinner"]'),
  ('rassie-van-der-dussen', 'Rassie van der Dussen', '["Top Order"]'),
  ('ravi-shah', 'Ravi Shah', '["Middle Order"]'),
  ('ravindra-jadeja', 'Ravindra Jadeja', '["All-rounder"]'),
  ('ravindu-shah', 'Ravindu Shah', '["Opener"]'),
  ('reece-topley', 'Reece Topley', '["Fast Bowler"]'),
  ('robert-van-oosterom', 'Robert van Oosterom', '["Opener"]'),
  ('robin-peterson', 'Robin Peterson', '["Spinner"]'),
  ('roelof-van-der-merwe', 'Roelof van der Merwe', '["Spinner"]'),
  ('roger-binny', 'Roger Binny', '["All-rounder"]'),
  ('roger-harper', 'Roger Harper', '["All-rounder"]'),
  ('rohit-sharma', 'Rohit Sharma', '["Opener"]'),
  ('roland-lefebvre', 'Roland Lefebvre', '["All-rounder"]'),
  ('romesh-kaluwitharana', 'Romesh Kaluwitharana', '["Opener", "Wicketkeeper"]'),
  ('roshan-mahanama', 'Roshan Mahanama', '["Middle Order"]'),
  ('ross-taylor', 'Ross Taylor', '["Middle Order"]'),
  ('rubel-hossain', 'Rubel Hossain', '["Fast Bowler"]'),
  ('ryan-klein', 'Ryan Klein', '["Fast Bowler"]'),
  ('ryan-ten-doeschate', 'Ryan ten Doeschate', '["All-rounder"]'),
  ('sabbir-rahman', 'Sabbir Rahman', '["Middle Order"]'),
  ('sachin-tendulkar', 'Sachin Tendulkar', '["Opener"]'),
  ('saleem-malik', 'Saleem Malik', '["Middle Order"]'),
  ('sam-curran', 'Sam Curran', '["All-rounder"]'),
  ('sanath-jayasuriya', 'Sanath Jayasuriya', '["Opener", "All-rounder"]'),
  ('sandeep-patil', 'Sandeep Patil', '["Middle Order"]'),
  ('scott-edwards', 'Scott Edwards', '["Wicketkeeper"]'),
  ('shakib-al-hasan', 'Shakib Al Hasan', '["All-rounder"]'),
  ('shaun-pollock', 'Shaun Pollock', '["All-rounder"]'),
  ('shreyas-iyer', 'Shreyas Iyer', '["Middle Order"]'),
  ('shubman-gill', 'Shubman Gill', '["Opener"]'),
  ('simon-o-donnell', 'Simon O''Donnell', '["All-rounder"]'),
  ('soumya-sarkar', 'Soumya Sarkar', '["Opener"]'),
  ('stefan-kelly', 'Stefan Kelly', '["Fast Bowler"]'),
  ('stephen-outerbridge', 'Stephen Outerbridge', '["Opener"]'),
  ('steve-tikolo', 'Steve Tikolo', '["Top Order"]'),
  ('stuart-carlisle', 'Stuart Carlisle', '["Middle Order"]'),
  ('sunil-gavaskar', 'Sunil Gavaskar', '["Opener"]'),
  ('suresh-raina', 'Suresh Raina', '["Middle Order"]'),
  ('suryakumar-yadav', 'Suryakumar Yadav', '["Middle Order"]'),
  ('sybrand-engelbrecht', 'Sybrand Engelbrecht', '["All-rounder"]'),
  ('syed-kirmani', 'Syed Kirmani', '["Wicketkeeper"]'),
  ('tabraiz-shamsi', 'Tabraiz Shamsi', '["Spinner"]'),
  ('tamim-iqbal', 'Tamim Iqbal', '["Opener"]'),
  ('teja-nidamanuru', 'Teja Nidamanuru', '["Middle Order"]'),
  ('temba-bavuma', 'Temba Bavuma', '["Top Order"]'),
  ('thomas-odoyo', 'Thomas Odoyo', '["All-rounder"]'),
  ('tim-de-leede', 'Tim de Leede', '["All-rounder"]'),
  ('tim-may', 'Tim May', '["Spinner"]'),
  ('tim-murtagh', 'Tim Murtagh', '["Fast Bowler"]'),
  ('tom-cooper', 'Tom Cooper', '["Middle Order"]'),
  ('tom-latham', 'Tom Latham', '["Wicketkeeper"]'),
  ('tony-suji', 'Tony Suji', '["Fast Bowler"]'),
  ('trent-boult', 'Trent Boult', '["Fast Bowler"]'),
  ('victor-grandia', 'Victor Grandia', '["Fast Bowler"]'),
  ('vikram-singh', 'Vikram Singh', '["Opener"]'),
  ('virat-kohli', 'Virat Kohli', '["Top Order", "Middle Order"]'),
  ('virender-sehwag', 'Virender Sehwag', '["Opener"]'),
  ('viv-richards', 'Viv Richards', '["Top Order"]'),
  ('waqar-younis', 'Waqar Younis', '["Fast Bowler"]'),
  ('wasim-akram', 'Wasim Akram', '["All-rounder"]'),
  ('wesley-barresi', 'Wesley Barresi', '["Wicketkeeper"]'),
  ('william-porterfield', 'William Porterfield', '["Opener"]'),
  ('yashpal-sharma', 'Yashpal Sharma', '["Top Order"]'),
  ('yuvraj-singh', 'Yuvraj Singh', '["All-rounder"]'),
  ('zaheer-khan', 'Zaheer Khan', '["Fast Bowler"]');
